version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:5.7.37
    environment:
      MYSQL_DATABASE: phpbb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always
    volumes:
      - ./init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  legacy-php:
    depends_on:
      - mysql
    image: php:5.3.29-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8002:80"
      - "33306:3306"